system:
    default:
        image_variations:
            editoImage:
                reference: ~
                filters:
                    geometry/scalewidth: [770]
                    geometry/crop: [770, 390, 0, 0]

