system:
    ezdemo_frontend_group:
        templating:
            module_layout: "BananamanuSimpleDesignBundle::pagelayout.html.twig"
            view_layout: "BananamanuSimpleDesignBundle::pagelayout.html.twig"
