siteaccess:
    groups:
        ezdemo_frontend_group:
            - ezdemo_site
            - ezdemo_site_user
            - eng
            - fre
system:
    ezdemo_frontend_group:
        user:
            layout: BananamanuSimpleDesignBundle::pagelayout.html.twig
        location_view:
            full:
                homepage:
                    template: "BananamanuSimpleDesignBundle:full:homepage.html.twig"
                    match:
                        Identifier\ContentType: [homepage]
                master:
                    controller: BananamanuSimpleDesignBundle:Master:viewLocationFull
                    template: "BananamanuSimpleDesignBundle:full:master.html.twig"
                    match:
                        Identifier\ContentType: [master]
                edito:
                    template: "BananamanuSimpleDesignBundle:full:edito.html.twig"
                    match:
                        Identifier\ContentType: [edito]
            line:
                edito:
                    template: "BananamanuSimpleDesignBundle:line:edito.html.twig"
                    match:
                        Identifier\ContentType: [edito]
        content_view:
            aside:
                default:
                    template: "BananamanuSimpleDesignBundle:aside:default.html.twig"
                    match:
                        Identifier\ContentType: [edito, master]
